name: Build for Android (Multi-ABI)

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86_64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - name: Build for ${{ matrix.abi }}
        run: |
          export ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          
          make clean || true
          ANDROID_ABI=${{ matrix.abi }} make -j

          # Collect into ABI-specific folder
          mkdir -p outputs/${{ matrix.abi }}
          cp -r build/bin/* outputs/${{ matrix.abi }}/

      - name: Upload Android binaries (combined)
        if: matrix.abi == 'x86_64'   # last run
        uses: actions/upload-artifact@v4
        with:
          name: whisper-android-multi-abi
          path: outputs/
