name: Build for Android

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build for Android arm64
        run: |
          docker run --rm -v $(pwd):/workdir \
            ghcr.io/ggerganov/whisper.cpp:android-build \
            bash -c "cd /workdir && ANDROID_ABI=arm64-v8a make"
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: whisper-android-arm64
          path: main
